// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQe7fTL8bF4SLCSPTqacpS0EHEK2Dm1m4',
    appId: '1:1073944324109:web:fcd4bbc9a7c5a979934d44',
    messagingSenderId: '1073944324109',
    projectId: 'foodzygo',
    authDomain: 'foodzygo.firebaseapp.com',
    storageBucket: 'foodzygo.firebasestorage.app',
    measurementId: 'G-CSMGYDYTBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgpX7-DJ8O-AhrFw_hVBX5EfvF0J3B5Zg',
    appId: '1:1073944324109:android:7f660c2db9ee62e6934d44',
    messagingSenderId: '1073944324109',
    projectId: 'foodzygo',
    storageBucket: 'foodzygo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTJGnY1RMveQtltzGEBQi3vBZTTCodCe8',
    appId: '1:1073944324109:ios:a3ccd51795be0795934d44',
    messagingSenderId: '1073944324109',
    projectId: 'foodzygo',
    storageBucket: 'foodzygo.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTJGnY1RMveQtltzGEBQi3vBZTTCodCe8',
    appId: '1:1073944324109:ios:a3ccd51795be0795934d44',
    messagingSenderId: '1073944324109',
    projectId: 'foodzygo',
    storageBucket: 'foodzygo.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQe7fTL8bF4SLCSPTqacpS0EHEK2Dm1m4',
    appId: '1:1073944324109:web:9e706a3a2673423f934d44',
    messagingSenderId: '1073944324109',
    projectId: 'foodzygo',
    authDomain: 'foodzygo.firebaseapp.com',
    storageBucket: 'foodzygo.firebasestorage.app',
    measurementId: 'G-83SX06Y7S2',
  );
}
